//
//  Untitled.proto
//  FeedsApp
//
//  Created by admin on 29/04/25.

// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: feeds.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - FeedsService

/// Namespace containing generated types for the "FeedsService" service.
internal enum FeedsService {
    /// Service descriptor for the "FeedsService" service.
    internal static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "FeedsService")
    /// Namespace for method metadata.
    internal enum Method {
        /// Namespace for "GetFeeds" metadata.
        internal enum GetFeeds {
            /// Request type for "GetFeeds".
            internal typealias Input = FeedsRequest
            /// Response type for "GetFeeds".
            internal typealias Output = FeedsResponse
            /// Descriptor for "GetFeeds".
            internal static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "FeedsService"),
                method: "GetFeeds"
            )
        }
        /// Descriptors for all methods in the "FeedsService" service.
        internal static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetFeeds.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "FeedsService" service.
    internal static let FeedsService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "FeedsService")
}

// MARK: FeedsService (server)

extension FeedsService {
    /// Streaming variant of the service protocol for the "FeedsService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    internal protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetFeeds" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `FeedsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `FeedsResponse` messages.
        func getFeeds(
            request: GRPCCore.StreamingServerRequest<FeedsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<FeedsResponse>
    }

    /// Service protocol for the "FeedsService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    internal protocol ServiceProtocol: FeedsService.StreamingServiceProtocol {
        /// Handle the "GetFeeds" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `FeedsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `FeedsResponse` message.
        func getFeeds(
            request: GRPCCore.ServerRequest<FeedsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<FeedsResponse>
    }

    /// Simple service protocol for the "FeedsService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    internal protocol SimpleServiceProtocol: FeedsService.ServiceProtocol {
        /// Handle the "GetFeeds" method.
        ///
        /// - Parameters:
        ///   - request: A `FeedsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `FeedsResponse` to respond with.
        func getFeeds(
            request: FeedsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> FeedsResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
extension FeedsService.StreamingServiceProtocol {
    internal func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: FeedsService.Method.GetFeeds.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<FeedsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<FeedsResponse>(),
            handler: { request, context in
                try await self.getFeeds(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension FeedsService.ServiceProtocol {
    internal func getFeeds(
        request: GRPCCore.StreamingServerRequest<FeedsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<FeedsResponse> {
        let response = try await self.getFeeds(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension FeedsService.SimpleServiceProtocol {
    internal func getFeeds(
        request: GRPCCore.ServerRequest<FeedsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<FeedsResponse> {
        return GRPCCore.ServerResponse<FeedsResponse>(
            message: try await self.getFeeds(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: FeedsService (client)

extension FeedsService {
    /// Generated client protocol for the "FeedsService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    internal protocol ClientProtocol: Sendable {
        /// Call the "GetFeeds" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `FeedsRequest` message.
        ///   - serializer: A serializer for `FeedsRequest` messages.
        ///   - deserializer: A deserializer for `FeedsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getFeeds<Result>(
            request: GRPCCore.ClientRequest<FeedsRequest>,
            serializer: some GRPCCore.MessageSerializer<FeedsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<FeedsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FeedsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "FeedsService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    internal struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        internal init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetFeeds" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `FeedsRequest` message.
        ///   - serializer: A serializer for `FeedsRequest` messages.
        ///   - deserializer: A deserializer for `FeedsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        internal func getFeeds<Result>(
            request: GRPCCore.ClientRequest<FeedsRequest>,
            serializer: some GRPCCore.MessageSerializer<FeedsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<FeedsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FeedsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: FeedsService.Method.GetFeeds.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension FeedsService.ClientProtocol {
    /// Call the "GetFeeds" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `FeedsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getFeeds<Result>(
        request: GRPCCore.ClientRequest<FeedsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FeedsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getFeeds(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<FeedsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<FeedsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension FeedsService.ClientProtocol {
    /// Call the "GetFeeds" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    internal func getFeeds<Result>(
        _ message: FeedsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<FeedsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<FeedsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getFeeds(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}
